name: Deploy to S3 + CloudFront

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET: simple-shoppingmall
  CF_DISTRIBUTION_ID: E1RH1GBM2V5D7A
  ROLE_TO_ASSUME: arn:aws:iam::305919526069:role/github-cicd

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: Upload hashed assets (immutable)
        run: |
          aws s3 sync dist s3://${S3_BUCKET} \
            --delete \
            --exclude "*" --include "assets/*" \
            --cache-control "public,max-age=31536000,immutable"

      - name: Upload the rest
        run: |
          aws s3 sync dist s3://${S3_BUCKET} \
            --exclude "assets/*" \
            --exclude "index.html"

      - name: Upload index.html as no-cache
        run: |
          aws s3 cp dist/index.html s3://${S3_BUCKET}/index.html \
            --cache-control "no-cache"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CF_DISTRIBUTION_ID }} \
            --paths "/index.html" "/"
